# Generated by Django 6.0.3 on 2026-04-02 11:54

import django.db.models.deletion
import django.utils.timezone
import gestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_guardia', models.CharField(choices=[('APOYO', 'Apoyo'), ('COORDINACION', 'Coordinación'), ('MAYOR55', 'Mayor de 55 años')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_guardia', to=settings.AUTH_USER_MODEL)),
                ('tramos_disponibles', models.ManyToManyField(related_name='maestros_disponibles', to='gestion.tramohorario')),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('clase', models.CharField(help_text='Ej: 3ºA, 5ºB', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales/', validators=[gestion.models.validar_tamano_archivo])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUBIERTA', 'Cubierta')], default='PENDIENTE', max_length=15)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas_registradas', to=settings.AUTH_USER_MODEL)),
                ('maestro_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sustituciones_asignadas', to='gestion.maestroguardia')),
                ('tramos_ausencia', models.ManyToManyField(related_name='faltas_afectadas', to='gestion.tramohorario')),
            ],
        ),
    ]
