# Generated by Django 6.0.3 on 2026-04-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_tramohorario_maestroguardia_falta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestroguardia',
            name='tramos_disponibles',
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=15)),
                ('maestro_guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='gestion.maestroguardia')),
                ('tramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tramohorario')),
            ],
            options={
                'unique_together': {('maestro_guardia', 'dia', 'tramo')},
            },
        ),
    ]
